[package]
name = "frontend-yew"
version = "0.0.1"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.74"
wee_alloc = "0.4.5"
console_error_panic_hook = "0.1.6"

yew = { path = "../../../tmp/yew/packages/yew" }
yew-router = { path = "../../../tmp/yew/packages/yew-router" }
yew-functional = { path = "../../../tmp/yew/packages/yew-functional" }
yew-services = { path = "../../../tmp/yew/packages/yew-services" }

graphql_client = "0.10.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
anyhow = "1.0.42"

toml = "0.5.8"
lazy_static = "1.4.0"
